spring:
  application:
    name: customer-api
  jackson:
    property-naming-strategy: SNAKE_CASE
  threads:
    virtual:
      enabled: true

server:
  port: 8081

management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTLP_TRACING_EXPORT_URL}
    logging:
      export:
        otlp:
          endpoint: ${OTLP_LOGGING_EXPORT_URL}

  tracing:
    propagation:
      produce: b3-multi, w3c  # Can produce B3 multi-header & W3C Trace Context
    sampling:
      probability: 1.0

  otlp:
    metrics:
      export:
        url: ${OTLP_METRICS_EXPORT_URL}
        step: 10s
        # enabled: false # Disables metrics export to keep the demo simple
        
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    '[org.zalando.logbook.Logbook]': TRACE  # https://www.baeldung.com/spring-logbook-http-logging
