server:
  port: 8090

spring:
  application:
    name: bff  # Identificador del servicio en Jaeger/Tempo/Grafana
    
  # WARNING: Enabling this property breaks Spring Boot Dashboard Live Data.
  # SNAKE_CASE breaks Spring Boot Dashboard Live Data because Actuator
  # metric fields are serialized as snake_case (e.g. available_tags),
  # while Spring Tools expects camelCase (e.g. availableTags).
  jackson:
    property-naming-strategy: SNAKE_CASE
  messages:
    basename:
    encoding: UTF-8
  threads:
    virtual:
      enabled: true
  task:
    execution:
      propagate-context: true
  
  http:
    serviceclient:
      customer-api:
        base-url: http://localhost:8081
        connect-timeout: 5000ms
        read-timeout: 10000ms
      product-api:
        base-url: http://localhost:8082
        connect-timeout: 5000ms
        read-timeout: 10000ms
      
  # Verify that the context is propagated to the reactive threads for tracing (e.g., WebClient, R2DBC, etc.)
  # By default in webflux, this is set to limited. This isn't needed if you are using WebClient.Builder
  # reactor:
  #   context-propagation: auto

logbook:
  predicate:
    exclude:
      - path: /actuator/**
  # strategy: body-only-if-status-at-least
  # minimum-status: 400
  format:
    style: curl

management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTLP_TRACING_EXPORT_URL}
    logging:
      export:
        otlp:
          # https://docs.spring.io/spring-boot/reference/actuator/loggers.html#actuator.loggers.opentelemetry
          # Currently not working without the following dependency:
          # io.opentelemtry.instrumentation:opentelemetry-logback-appender
          endpoint: ${OTLP_LOGGING_EXPORT_URL}

  tracing:
    propagation:
      consume: w3c # Only accept W3C Trace Context headers
      produce: b3-multi, w3c  # Can produce B3 multi-header & W3C Trace Context
    sampling:
      probability: 1.0

  otlp:
    metrics:
      export:
        url: ${OTLP_METRICS_EXPORT_URL}
        step: 10s
        # enabled: false # Disables metrics export to keep the demo simple

  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    '[org.zalando.logbook.Logbook]': TRACE  # https://www.baeldung.com/spring-logbook-http-logging